-- 更新 POI 表的 poi_type 枚举类型
ALTER TABLE poi 
MODIFY COLUMN poi_type ENUM(
    'WAREHOUSE',
    'DISTRIBUTION_CENTER',
    'FACTORY',
    'GAS_STATION',
    'MAINTENANCE_CENTER',
    'REST_AREA',
    'MATERIAL_MARKET',
    'VEGETABLE_BASE',
    'VEGETABLE_MARKET',
    'TEST',
    'AUTO_ASSEMBLY_PLANT',
    'BOARD_FACTORY',
    'FURNITURE_FACTORY',
    'IRON_MINE',
    'RUBBER_PROCESSING_PLANT',
    'SAWMILL',
    'STEEL_MILL',
    'STEEL_PROCESSING_PLANT',
    'TIMBER_YARD',
    'TIRE_MANUFACTURING_PLANT'
) COMMENT 'POI 类型';
