SET NAMES utf8mb4;
SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
SET SESSION time_zone = '+08:00';
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `action`;
CREATE TABLE `action` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action_name` varchar(100) NOT NULL,
  `action_type` enum('LOAD','MAINTENANCE','MOVE_TO','REFUEL','REPORT','REST','UNLOAD','WAIT') NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_time` datetime(6) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `duration_minutes` int(11) DEFAULT NULL,
  `is_locked` bit(1) DEFAULT NULL,
  `target_poi_id` bigint(20) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `assignment`;
CREATE TABLE `assignment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action_line` text DEFAULT NULL,
  `created_time` datetime(6) DEFAULT NULL,
  `current_action_index` int(11) DEFAULT 0,
  `end_time` datetime(6) DEFAULT NULL,
  `start_time` datetime(6) DEFAULT NULL,
  `status` enum('ASSIGNED','CANCELLED','COMPLETED','DELAYED','FAILED','IN_PROGRESS','WAITING') NOT NULL,
  `updated_by` varchar(75) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `driver_id` bigint(20) DEFAULT NULL,
  `vehicle_id` bigint(20) DEFAULT NULL,
  `route_id` bigint(20) DEFAULT NULL,
  `actual_output_weight` double DEFAULT NULL,
  `cargo_type` varchar(100) DEFAULT NULL,
  `chain_code` varchar(50) DEFAULT NULL,
  `chain_name` varchar(100) DEFAULT NULL,
  `delivery_appoint` datetime(6) DEFAULT NULL,
  `empty_driving_distance_km` double DEFAULT NULL,
  `empty_driving_time_seconds` bigint(20) DEFAULT NULL,
  `expected_output_weight` double DEFAULT NULL,
  `expected_yield_rate` double DEFAULT NULL,
  `loading_wait_time` bigint(20) DEFAULT NULL,
  `pickup_appoint` datetime(6) DEFAULT NULL,
  `processing_actual_finish_time` datetime(6) DEFAULT NULL,
  `is_processing_assignment` bit(1) DEFAULT NULL,
  `processing_expected_finish_time` datetime(6) DEFAULT NULL,
  `processing_start_time` datetime(6) DEFAULT NULL,
  `processing_status` enum('CANCELLED','COMPLETED','IN_PROCESS','PENDING') DEFAULT NULL,
  `total_driving_distance` double DEFAULT NULL,
  `total_driving_time` bigint(20) DEFAULT NULL,
  `unloading_wait_time` bigint(20) DEFAULT NULL,
  `waiting_assignment_time` bigint(20) DEFAULT NULL,
  `customer_id` bigint(20) DEFAULT NULL,
  `dest_poi_id` bigint(20) NOT NULL,
  `origin_poi_id` bigint(20) NOT NULL,
  `processing_chain_id` bigint(20) DEFAULT NULL,
  `empty_distance_meters` double DEFAULT NULL,
  `empty_driving_seconds` bigint(20) DEFAULT NULL,
  `loaded_distance_meters` double DEFAULT NULL,
  `loaded_driving_seconds` bigint(20) DEFAULT NULL,
  `loading_wait_seconds` bigint(20) DEFAULT NULL,
  `total_distance_meters` double DEFAULT NULL,
  `total_driving_seconds` bigint(20) DEFAULT NULL,
  `unloading_wait_seconds` bigint(20) DEFAULT NULL,
  `waiting_assignment_seconds` bigint(20) DEFAULT NULL,
  `current_leg_index` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_status` (`status`),
  KEY `idx_assignment_vehicle` (`vehicle_id`),
  KEY `idx_assignment_driver` (`driver_id`),
  KEY `idx_assignment_route` (`route_id`),
  KEY `FK2rb2gupg477eugn9xreb8n9f7` (`customer_id`),
  KEY `FKijie71is1yqx9j6pcnvc0qx4x` (`dest_poi_id`),
  KEY `FKp86ivtervtht52vpdlg54aio1` (`origin_poi_id`),
  KEY `FKal4a7tdb0n5ukt7tud0r60gqr` (`processing_chain_id`),
  CONSTRAINT `FK2rb2gupg477eugn9xreb8n9f7` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FK5s0h3p6bsdhaysqgk03dg10px` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`),
  CONSTRAINT `FK9xmipp4eby5guoy5xxt8unbfc` FOREIGN KEY (`route_id`) REFERENCES `route` (`id`),
  CONSTRAINT `FKal4a7tdb0n5ukt7tud0r60gqr` FOREIGN KEY (`processing_chain_id`) REFERENCES `processing_chain` (`id`),
  CONSTRAINT `FKijie71is1yqx9j6pcnvc0qx4x` FOREIGN KEY (`dest_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKlxyhk53rm4gb54bfipxr2i8p8` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`),
  CONSTRAINT `FKp86ivtervtht52vpdlg54aio1` FOREIGN KEY (`origin_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `assignment_leg`;
CREATE TABLE `assignment_leg` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `carried_shipment_item_ids` text DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `distance_meters` double DEFAULT NULL,
  `driving_seconds` bigint(20) DEFAULT NULL,
  `load_state` enum('EMPTY','LOADED') NOT NULL,
  `sequence_index` int(11) NOT NULL,
  `assignment_id` bigint(20) NOT NULL,
  `from_node_id` bigint(20) DEFAULT NULL,
  `from_poi_id` bigint(20) DEFAULT NULL,
  `to_node_id` bigint(20) DEFAULT NULL,
  `to_poi_id` bigint(20) NOT NULL,
  `vehicle_id` bigint(20) DEFAULT NULL,
  `completed_sim_time` datetime(6) DEFAULT NULL,
  `current_load_tonnes` double NOT NULL DEFAULT 0,
  `executed_distance_meters` double NOT NULL DEFAULT 0,
  `executed_driving_seconds` bigint(20) NOT NULL DEFAULT 0,
  `last_processed_loop_index` int(11) DEFAULT NULL,
  `progress_status` enum('COMPLETED','PENDING','RUNNING') NOT NULL,
  `started_sim_time` datetime(6) DEFAULT NULL,
  `version` bigint(20) NOT NULL DEFAULT 0,
  `from_latitude` double DEFAULT NULL,
  `from_longitude` double DEFAULT NULL,
  `to_latitude` double DEFAULT NULL,
  `to_longitude` double DEFAULT NULL,
  `emission_model_id` varchar(80) DEFAULT NULL,
  `energy_fact_status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `executed_emission_kg` double NOT NULL DEFAULT 0,
  `executed_energy_liters` double NOT NULL DEFAULT 0,
  `vehicle_emission_class_code` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_assignment_leg_assignment_sequence` (`assignment_id`,`sequence_index`),
  KEY `idx_assignment_leg_assignment` (`assignment_id`),
  KEY `idx_assignment_leg_vehicle` (`vehicle_id`),
  KEY `idx_assignment_leg_load_state` (`load_state`),
  KEY `FKqyj55a6nwgp7x2mg9180uqclo` (`from_node_id`),
  KEY `FKiwfno19x69xah9fyu0m7ax6ke` (`from_poi_id`),
  KEY `FKe51xtcm8jf1j1vke7cn1bdnkx` (`to_node_id`),
  KEY `FKhanq69362y78rxn11i2u4ljky` (`to_poi_id`),
  KEY `idx_assignment_leg_assignment_progress` (`assignment_id`,`progress_status`),
  CONSTRAINT `FK1ckp79lh7jppx4tpwsm2npq6p` FOREIGN KEY (`assignment_id`) REFERENCES `assignment` (`id`),
  CONSTRAINT `FKe51xtcm8jf1j1vke7cn1bdnkx` FOREIGN KEY (`to_node_id`) REFERENCES `assignment_nodes` (`id`),
  CONSTRAINT `FKhanq69362y78rxn11i2u4ljky` FOREIGN KEY (`to_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKiwfno19x69xah9fyu0m7ax6ke` FOREIGN KEY (`from_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKoqdmk10fhu0air14ecl89njxk` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`),
  CONSTRAINT `FKqyj55a6nwgp7x2mg9180uqclo` FOREIGN KEY (`from_node_id`) REFERENCES `assignment_nodes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `assignment_nodes`;
CREATE TABLE `assignment_nodes` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action_type` enum('LOAD','PASS_BY','UNLOAD') NOT NULL,
  `actual_arrival_time` datetime(6) DEFAULT NULL,
  `is_completed` bit(1) NOT NULL,
  `sequence_index` int(11) NOT NULL,
  `volume_delta` double NOT NULL,
  `weight_delta` double NOT NULL,
  `assignment_id` bigint(20) NOT NULL,
  `poi_id` bigint(20) NOT NULL,
  `shipment_item_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKeyx7thllqaioo4oj6nq430tsc` (`assignment_id`),
  KEY `FKk5pburnnwekov72lomydpyrp0` (`poi_id`),
  KEY `FK6mrt0umdru6ygoh17ha2jmhli` (`shipment_item_id`),
  CONSTRAINT `FK6mrt0umdru6ygoh17ha2jmhli` FOREIGN KEY (`shipment_item_id`) REFERENCES `shipment_item` (`id`),
  CONSTRAINT `FKeyx7thllqaioo4oj6nq430tsc` FOREIGN KEY (`assignment_id`) REFERENCES `assignment` (`id`),
  CONSTRAINT `FKk5pburnnwekov72lomydpyrp0` FOREIGN KEY (`poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `cargo_wait_episode`;
CREATE TABLE `cargo_wait_episode` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ended_sim_time` datetime(6) DEFAULT NULL,
  `last_observed_sim_time` datetime(6) NOT NULL,
  `outcome` enum('CANCELLED','OPEN','TRANSPORT_STARTED') NOT NULL,
  `shipment_item_id` bigint(20) NOT NULL,
  `simulation_run_id` varchar(100) NOT NULL,
  `start_source` enum('ENTITY_CREATED_TIME','FIRST_OBSERVED_TICK') NOT NULL,
  `started_sim_time` datetime(6) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  `weight_tonnes` double NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cargo_wait_run_item` (`simulation_run_id`,`shipment_item_id`),
  KEY `idx_cargo_wait_run` (`simulation_run_id`),
  KEY `idx_cargo_wait_run_outcome` (`simulation_run_id`,`outcome`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `address` varchar(200) DEFAULT NULL,
  `code` varchar(50) NOT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `contact_phone` varchar(20) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_code` (`code`),
  KEY `idx_customer_code` (`code`),
  KEY `idx_customer_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `delivery_sla_fact`;
CREATE TABLE `delivery_sla_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `delivered_sim_time` datetime(6) DEFAULT NULL,
  `delivery_assignment_id` bigint(20) DEFAULT NULL,
  `delivery_deadline_sim_time` datetime(6) NOT NULL,
  `demand_created_sim_time` datetime(6) NOT NULL,
  `haversine_distance_km` double NOT NULL,
  `max_service_wait_seconds` bigint(20) NOT NULL,
  `reference_road_distance_km` double NOT NULL,
  `reference_speed_kph` double NOT NULL,
  `road_distance_factor` double NOT NULL,
  `shipment_item_id` bigint(20) NOT NULL,
  `simulation_run_id` varchar(100) NOT NULL,
  `sla_model_id` varchar(80) NOT NULL,
  `sla_seconds` bigint(20) NOT NULL,
  `status` enum('CANCELLED','DELIVERED','OPEN') NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_sla_run_item` (`simulation_run_id`,`shipment_item_id`),
  KEY `idx_delivery_sla_run` (`simulation_run_id`),
  KEY `idx_delivery_sla_run_status` (`simulation_run_id`,`status`),
  KEY `idx_delivery_sla_assignment` (`delivery_assignment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `dispatch_comparison_cost_snapshot`;
CREATE TABLE `dispatch_comparison_cost_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `all_cost` double DEFAULT NULL,
  `completed_items` int(11) DEFAULT NULL,
  `cost_a` double DEFAULT NULL,
  `cost_b` double DEFAULT NULL,
  `cost_c` double DEFAULT NULL,
  `cost_d` double DEFAULT NULL,
  `cost_e` double DEFAULT NULL,
  `loop_count` int(11) DEFAULT NULL,
  `normalized_all_cost` double DEFAULT NULL,
  `recorded_at` datetime(6) DEFAULT NULL,
  `sim_time` datetime(6) DEFAULT NULL,
  `total_items` int(11) DEFAULT NULL,
  `strategy_run_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKixsnpfchkty2722uxxywospi3` (`strategy_run_id`),
  CONSTRAINT `FKixsnpfchkty2722uxxywospi3` FOREIGN KEY (`strategy_run_id`) REFERENCES `dispatch_comparison_strategy_run` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `dispatch_comparison_experiment_run`;
CREATE TABLE `dispatch_comparison_experiment_run` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `completed_items` int(11) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `current_loop` int(11) DEFAULT NULL,
  `current_strategy` varchar(20) DEFAULT NULL,
  `ended_at` datetime(6) DEFAULT NULL,
  `experiment_id` varchar(80) NOT NULL,
  `failure_reason` varchar(1000) DEFAULT NULL,
  `max_loops` int(11) DEFAULT NULL,
  `scenario_json` text DEFAULT NULL,
  `shipment_count` int(11) DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `status` enum('ABORTED','COMPLETED','FAILED','PAUSED_HEURISTIC','PAUSED_ORIGINAL','PREPARED','REBUILDING_FOR_HEURISTIC','RUNNING_HEURISTIC','RUNNING_ORIGINAL') NOT NULL,
  `total_items` int(11) DEFAULT NULL,
  `vehicle_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `dispatch_comparison_strategy_run`;
CREATE TABLE `dispatch_comparison_strategy_run` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `all_cost` double DEFAULT NULL,
  `assignment_count` int(11) DEFAULT NULL,
  `completed_items` int(11) DEFAULT NULL,
  `cost_a` double DEFAULT NULL,
  `cost_b` double DEFAULT NULL,
  `cost_c` double DEFAULT NULL,
  `cost_d` double DEFAULT NULL,
  `cost_e` double DEFAULT NULL,
  `ended_at` datetime(6) DEFAULT NULL,
  `loop_count` int(11) DEFAULT NULL,
  `normalized_all_cost` double DEFAULT NULL,
  `normalized_cost_a` double DEFAULT NULL,
  `normalized_cost_b` double DEFAULT NULL,
  `normalized_cost_c` double DEFAULT NULL,
  `normalized_cost_d` double DEFAULT NULL,
  `normalized_cost_e` double DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `status` enum('ABORTED','COMPLETED','FAILED','PAUSED','RUNNING') NOT NULL,
  `strategy` varchar(20) NOT NULL,
  `total_items` int(11) DEFAULT NULL,
  `vehicle_used_count` int(11) DEFAULT NULL,
  `experiment_run_id` bigint(20) NOT NULL,
  `experiment_normalization_baseline_percentile` varchar(10) DEFAULT NULL,
  `experiment_normalization_baseline_strategy` varchar(20) DEFAULT NULL,
  `experiment_normalization_scope` varchar(40) DEFAULT NULL,
  `experiment_normalized_all_cost` double DEFAULT NULL,
  `experiment_normalized_cost_a` double DEFAULT NULL,
  `experiment_normalized_cost_b` double DEFAULT NULL,
  `experiment_normalized_cost_c` double DEFAULT NULL,
  `experiment_normalized_cost_d` double DEFAULT NULL,
  `experiment_normalized_cost_e` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKcu636nbrga9rpj9umfdd4cgs9` (`experiment_run_id`),
  CONSTRAINT `FKcu636nbrga9rpj9umfdd4cgs9` FOREIGN KEY (`experiment_run_id`) REFERENCES `dispatch_comparison_experiment_run` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `driver`;
CREATE TABLE `driver` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) DEFAULT NULL,
  `current_status` enum('ASSIGNED','IDLE','MAINTENANCE','OFF','REJECTING') DEFAULT NULL,
  `driver_name` varchar(255) DEFAULT NULL,
  `driver_phone` varchar(255) DEFAULT NULL,
  `pref_cargo` varchar(50) DEFAULT NULL,
  `pref_max_distance_km` double DEFAULT NULL,
  `pref_max_weight_tons` double DEFAULT NULL,
  `reserved_replacement_event_id` bigint DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `assignment_driver_history`;
CREATE TABLE `assignment_driver_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action` enum('BIND','RELEASE') NOT NULL,
  `actor` varchar(50) DEFAULT NULL,
  `assignment_id` bigint(20) NOT NULL,
  `created_time` datetime(6) DEFAULT NULL,
  `driver_id` bigint(20) NOT NULL,
  `driver_name` varchar(50) DEFAULT NULL,
  `from_status` varchar(20) DEFAULT NULL,
  `reason` varchar(100) DEFAULT NULL,
  `sim_time` datetime(6) DEFAULT NULL,
  `to_status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_driver_history_assignment` (`assignment_id`),
  KEY `idx_assignment_driver_history_driver` (`driver_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `driver_vehicle`;
CREATE TABLE `driver_vehicle` (
  `driver_id` bigint(20) NOT NULL,
  `vehicle_id` bigint(20) NOT NULL,
  PRIMARY KEY (`driver_id`,`vehicle_id`),
  KEY `FK3vmlntx03j2lwhnuofohs1jow` (`vehicle_id`),
  CONSTRAINT `FK3vmlntx03j2lwhnuofohs1jow` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`),
  CONSTRAINT `FKj049vjpgcr1l40w0bura00fyw` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `enrollment`;
CREATE TABLE `enrollment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `goods_id` bigint(20) DEFAULT NULL,
  `poi_id` bigint(20) DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_poi_goods` (`poi_id`,`goods_id`),
  KEY `FKos6cwjg0fgk6j8ss0ycmwxf70` (`goods_id`),
  CONSTRAINT `FKey5rp7ttvh0msnm0tde4bphcm` FOREIGN KEY (`poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKos6cwjg0fgk6j8ss0ycmwxf70` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `evaluation_snapshot_history`;
CREATE TABLE `evaluation_snapshot_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `contract_version` varchar(24) NOT NULL,
  `loop_index` int(11) NOT NULL,
  `run_kind` enum('DISPATCH_COMPARISON','REGULAR') NOT NULL,
  `sim_time` datetime(6) NOT NULL,
  `simulation_run_id` varchar(100) NOT NULL,
  `snapshot_payload_json` longtext NOT NULL,
  `snapshot_revision` bigint(20) NOT NULL,
  `snapshot_status` enum('COMPLETE','FAILED','PARTIAL') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_evaluation_history_run_revision` (`simulation_run_id`,`snapshot_revision`),
  KEY `idx_evaluation_history_run_loop` (`simulation_run_id`,`loop_index`),
  KEY `idx_evaluation_history_run_time` (`simulation_run_id`,`sim_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `goods`;
CREATE TABLE `goods` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `category` varchar(100) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `hazmat_level` varchar(50) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `require_temp` bit(1) DEFAULT NULL,
  `shelf_life_days` int(11) DEFAULT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `volume_per_unit` double DEFAULT NULL,
  `weight_per_unit` double DEFAULT NULL,
  `vehicle_fit` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_sku` (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `node_service_episode`;
CREATE TABLE `node_service_episode` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action_type` enum('LOAD','UNLOAD') NOT NULL,
  `arrived_at` datetime(6) NOT NULL,
  `assignment_id` bigint(20) NOT NULL,
  `assignment_node_id` bigint(20) DEFAULT NULL,
  `event_key` varchar(190) NOT NULL,
  `leg_sequence_index` int(11) DEFAULT NULL,
  `poi_id` bigint(20) NOT NULL,
  `processed_tonnes` double DEFAULT NULL,
  `service_completed_at` datetime(6) DEFAULT NULL,
  `service_started_at` datetime(6) NOT NULL,
  `status` enum('COMPLETED','IN_SERVICE') NOT NULL,
  `vehicle_id` bigint(20) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_node_service_episode_event_key` (`event_key`),
  KEY `idx_node_service_assignment` (`assignment_id`),
  KEY `idx_node_service_node` (`assignment_node_id`),
  KEY `idx_node_service_status_completed` (`status`,`service_completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `poi`;
CREATE TABLE `poi` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) DEFAULT NULL,
  `latitude` decimal(10,6) NOT NULL COMMENT '纬度（范围：-90~90，精度6位小数）',
  `longitude` decimal(9,6) NOT NULL COMMENT '经度（范围：-180~180，精度6位小数）',
  `name` varchar(255) NOT NULL,
  `poi_type` varchar(30) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_chain`;
CREATE TABLE `processing_chain` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `chain_code` varchar(50) NOT NULL,
  `chain_name` varchar(100) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `input_materials` text DEFAULT NULL,
  `input_weight_per_cycle` double DEFAULT NULL,
  `merge_stage_id` bigint(20) DEFAULT NULL,
  `output_weight_per_cycle` double DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','MAINTENANCE') NOT NULL,
  `total_processing_time_minutes` int(11) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `yield_rate` double DEFAULT NULL,
  `processing_seconds` bigint(20) DEFAULT NULL,
  `total_elapsed_seconds` bigint(20) DEFAULT NULL,
  `transport_distance_meters` double DEFAULT NULL,
  `transport_driving_seconds` bigint(20) DEFAULT NULL,
  `waiting_seconds` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK2ee9tks2yfksvwerxoupcm3uq` (`chain_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_chain_predecessors`;
CREATE TABLE `processing_chain_predecessors` (
  `chain_id` bigint(20) NOT NULL,
  `predecessor_chain_id` bigint(20) DEFAULT NULL,
  KEY `FKjdadnird3r9kulg872psksx3x` (`chain_id`),
  CONSTRAINT `FKjdadnird3r9kulg872psksx3x` FOREIGN KEY (`chain_id`) REFERENCES `processing_chain` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_execution_flow`;
CREATE TABLE `processing_execution_flow` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actual_weight` double DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `input_key` varchar(50) NOT NULL,
  `planned_weight` double NOT NULL,
  `sku` varchar(100) NOT NULL,
  `status` enum('CANCELLED','DELIVERED','FAILED','IN_TRANSIT','PLANNED','WAITING_TRANSPORT') NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `batch_id` bigint(20) NOT NULL,
  `from_execution_id` bigint(20) DEFAULT NULL,
  `plan_flow_id` bigint(20) NOT NULL,
  `shipment_id` bigint(20) DEFAULT NULL,
  `to_execution_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_execution_flow` (`batch_id`,`to_execution_id`,`input_key`),
  KEY `idx_processing_execution_flow_batch` (`batch_id`),
  KEY `idx_processing_execution_flow_from` (`from_execution_id`),
  KEY `idx_processing_execution_flow_to` (`to_execution_id`),
  KEY `idx_processing_execution_flow_shipment` (`shipment_id`),
  KEY `FKjm2mvegq6hhr974gct3o3eylc` (`plan_flow_id`),
  CONSTRAINT `FK69se2qaa530vfl71xmnp0wpkr` FOREIGN KEY (`batch_id`) REFERENCES `production_batch` (`id`),
  CONSTRAINT `FK7wg1dcdb9iui35eb0rv8k2cfi` FOREIGN KEY (`shipment_id`) REFERENCES `shipment` (`id`),
  CONSTRAINT `FKchdmqmh2jngf7qdd7pa91djs4` FOREIGN KEY (`to_execution_id`) REFERENCES `processing_stage_execution` (`id`),
  CONSTRAINT `FKjm2mvegq6hhr974gct3o3eylc` FOREIGN KEY (`plan_flow_id`) REFERENCES `production_plan_flow` (`id`),
  CONSTRAINT `FKpa0g3h2qy8m1jbl34f7rr2i9u` FOREIGN KEY (`from_execution_id`) REFERENCES `processing_stage_execution` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_stage`;
CREATE TABLE `processing_stage` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `input_goods_sku` varchar(50) DEFAULT NULL,
  `input_weight_ratio` double DEFAULT NULL,
  `max_capacity_per_cycle` double DEFAULT NULL,
  `min_batch_size` double DEFAULT NULL,
  `output_goods_sku` varchar(50) DEFAULT NULL,
  `output_weight_ratio` double DEFAULT NULL,
  `processing_time_minutes` int(11) NOT NULL,
  `stage_name` varchar(100) NOT NULL,
  `stage_order` int(11) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `input_goods_id` bigint(20) DEFAULT NULL,
  `output_goods_id` bigint(20) DEFAULT NULL,
  `chain_id` bigint(20) NOT NULL,
  `poi_id` bigint(20) NOT NULL,
  `processing_seconds` bigint(20) DEFAULT NULL,
  `total_elapsed_seconds` bigint(20) DEFAULT NULL,
  `transport_distance_meters` double DEFAULT NULL,
  `transport_driving_seconds` bigint(20) DEFAULT NULL,
  `waiting_seconds` bigint(20) DEFAULT NULL,
  `stage_key` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_stage_key` (`chain_id`,`stage_key`),
  KEY `FKdawoog9h5t1ceitb1nqb5m4qt` (`input_goods_id`),
  KEY `FK51taftfnnyxl7ed5mfsxw32uf` (`output_goods_id`),
  KEY `FK2kkg1kngkh62h2cufhjxyfj0b` (`poi_id`),
  CONSTRAINT `FK2kkg1kngkh62h2cufhjxyfj0b` FOREIGN KEY (`poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FK51taftfnnyxl7ed5mfsxw32uf` FOREIGN KEY (`output_goods_id`) REFERENCES `goods` (`id`),
  CONSTRAINT `FKdawoog9h5t1ceitb1nqb5m4qt` FOREIGN KEY (`input_goods_id`) REFERENCES `goods` (`id`),
  CONSTRAINT `FKkb7jcuc70q3ti8iiolfeefkm` FOREIGN KEY (`chain_id`) REFERENCES `processing_chain` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_stage_edge`;
CREATE TABLE `processing_stage_edge` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `chain_id` bigint(20) NOT NULL,
  `from_stage_id` bigint(20) NOT NULL,
  `to_stage_id` bigint(20) NOT NULL,
  `to_stage_input_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_stage_edge_input` (`to_stage_input_id`),
  UNIQUE KEY `uk_processing_stage_edge` (`from_stage_id`,`to_stage_id`,`to_stage_input_id`),
  KEY `idx_processing_stage_edge_chain` (`chain_id`),
  KEY `idx_processing_stage_edge_from` (`from_stage_id`),
  KEY `idx_processing_stage_edge_to` (`to_stage_id`),
  CONSTRAINT `FKea5s857vhaliyna7leoh31a00` FOREIGN KEY (`from_stage_id`) REFERENCES `processing_stage` (`id`),
  CONSTRAINT `FKm31cpbjkan14jmkxl7g7rks17` FOREIGN KEY (`to_stage_input_id`) REFERENCES `processing_stage_input` (`id`),
  CONSTRAINT `FKq4xolbb7yt726tunyglgm2w0` FOREIGN KEY (`chain_id`) REFERENCES `processing_chain` (`id`),
  CONSTRAINT `FKwsbacm6qkmt6fayyfyhv7ott` FOREIGN KEY (`to_stage_id`) REFERENCES `processing_stage` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_stage_execution`;
CREATE TABLE `processing_stage_execution` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actual_input_weight` double DEFAULT NULL,
  `actual_output_weight` double DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `progress_percent` int(11) DEFAULT NULL,
  `stage_order` int(11) NOT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `status` enum('CANCELLED','COMPLETED','FAILED','PROCESSING','READY_TO_PROCESS','WAITING_INPUT') NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `batch_id` bigint(20) NOT NULL,
  `inbound_shipment_id` bigint(20) DEFAULT NULL,
  `outbound_shipment_id` bigint(20) DEFAULT NULL,
  `plan_node_id` bigint(20) NOT NULL,
  `processing_poi_id` bigint(20) NOT NULL,
  `stage_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_stage_execution` (`batch_id`,`stage_order`),
  KEY `idx_stage_execution_batch` (`batch_id`),
  KEY `idx_stage_execution_stage` (`stage_id`),
  KEY `idx_stage_execution_status` (`status`),
  KEY `idx_stage_execution_inbound` (`inbound_shipment_id`),
  KEY `idx_stage_execution_outbound` (`outbound_shipment_id`),
  KEY `FKdi2bl1f64m0bp8tho7pw2jnef` (`plan_node_id`),
  KEY `FKa1xjhn2sywbfebhiayuay72u` (`processing_poi_id`),
  CONSTRAINT `FKa1xjhn2sywbfebhiayuay72u` FOREIGN KEY (`processing_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKcknh9gjx1v2ygld8x3wq0aqcw` FOREIGN KEY (`batch_id`) REFERENCES `production_batch` (`id`),
  CONSTRAINT `FKdi2bl1f64m0bp8tho7pw2jnef` FOREIGN KEY (`plan_node_id`) REFERENCES `production_plan_node` (`id`),
  CONSTRAINT `FKj19uii2arlw0wglafkh8i68sr` FOREIGN KEY (`inbound_shipment_id`) REFERENCES `shipment` (`id`),
  CONSTRAINT `FKlxac7qvmubv63arxxcv9ojqqx` FOREIGN KEY (`outbound_shipment_id`) REFERENCES `shipment` (`id`),
  CONSTRAINT `FKr66dwbiiucm66ikssa1gscpqy` FOREIGN KEY (`stage_id`) REFERENCES `processing_stage` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `processing_stage_input`;
CREATE TABLE `processing_stage_input` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `input_key` varchar(50) NOT NULL,
  `input_share` double NOT NULL,
  `sku` varchar(100) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `goods_id` bigint(20) DEFAULT NULL,
  `stage_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_stage_input` (`stage_id`,`input_key`),
  KEY `idx_processing_stage_input_stage` (`stage_id`),
  KEY `FKb611kmhccvxc77n4w5n9im33l` (`goods_id`),
  CONSTRAINT `FKb611kmhccvxc77n4w5n9im33l` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`),
  CONSTRAINT `FKiskm8cb1y618cwgfydjglxk1c` FOREIGN KEY (`stage_id`) REFERENCES `processing_stage` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `production_batch`;
CREATE TABLE `production_batch` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actual_final_output_weight` double DEFAULT NULL,
  `batch_no` varchar(50) NOT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `planned_final_output_weight` double DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `status` enum('CANCELLED','COMPLETED','CREATED','FAILED','INBOUND_TRANSPORT','INTER_STAGE_TRANSPORT','PROCESSING','WAITING_MATERIAL') NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `chain_id` bigint(20) NOT NULL,
  `plan_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_production_batch_no` (`batch_no`),
  KEY `idx_production_batch_plan` (`plan_id`),
  KEY `idx_production_batch_status` (`status`),
  KEY `FKqj88yg0dluljqlp7x89fpcawi` (`chain_id`),
  CONSTRAINT `FKou4w13cmjm901cd8c3e93aecy` FOREIGN KEY (`plan_id`) REFERENCES `production_plan` (`id`),
  CONSTRAINT `FKqj88yg0dluljqlp7x89fpcawi` FOREIGN KEY (`chain_id`) REFERENCES `processing_chain` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `production_plan`;
CREATE TABLE `production_plan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `final_demand_weight` double NOT NULL,
  `final_sku` varchar(100) DEFAULT NULL,
  `plan_no` varchar(50) NOT NULL,
  `random_seed` bigint(20) DEFAULT NULL,
  `simulation_run_id` varchar(64) DEFAULT NULL,
  `generation_round` int(11) DEFAULT NULL,
  `status` enum('CALCULATED','CANCELLED','DRAFT','RELEASED') NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `chain_id` bigint(20) NOT NULL,
  `source_poi_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_production_plan_no` (`plan_no`),
  UNIQUE KEY `uk_production_plan_generation` (`simulation_run_id`,`generation_round`,`chain_id`),
  KEY `idx_production_plan_chain` (`chain_id`),
  KEY `idx_production_plan_status` (`status`),
  KEY `FKtnb6kfcpad4qu79alwsid3jsm` (`source_poi_id`),
  KEY `idx_production_plan_run_round` (`simulation_run_id`,`generation_round`),
  CONSTRAINT `FKl38bt89883cwbi99dskxmle9x` FOREIGN KEY (`chain_id`) REFERENCES `processing_chain` (`id`),
  CONSTRAINT `FKtnb6kfcpad4qu79alwsid3jsm` FOREIGN KEY (`source_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `production_plan_flow`;
CREATE TABLE `production_plan_flow` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `input_key` varchar(50) NOT NULL,
  `planned_weight` double NOT NULL,
  `sku` varchar(100) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `from_node_id` bigint(20) DEFAULT NULL,
  `plan_id` bigint(20) NOT NULL,
  `source_poi_id` bigint(20) DEFAULT NULL,
  `stage_input_id` bigint(20) DEFAULT NULL,
  `to_node_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_production_plan_flow` (`plan_id`,`to_node_id`,`input_key`),
  KEY `idx_production_plan_flow_plan` (`plan_id`),
  KEY `idx_production_plan_flow_from` (`from_node_id`),
  KEY `idx_production_plan_flow_to` (`to_node_id`),
  KEY `FKl6wip2rg4l2s0hkwgvpeh9e0q` (`source_poi_id`),
  KEY `FKaeyfjroyph3smw2evrqj46y5f` (`stage_input_id`),
  CONSTRAINT `FK2eiccmkrksap5gl8hj17e8bgw` FOREIGN KEY (`from_node_id`) REFERENCES `production_plan_node` (`id`),
  CONSTRAINT `FKaeyfjroyph3smw2evrqj46y5f` FOREIGN KEY (`stage_input_id`) REFERENCES `processing_stage_input` (`id`),
  CONSTRAINT `FKajgcl6tr6la5ihuhmaiojmf5m` FOREIGN KEY (`plan_id`) REFERENCES `production_plan` (`id`),
  CONSTRAINT `FKl6wip2rg4l2s0hkwgvpeh9e0q` FOREIGN KEY (`source_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKlv52apwf0y12kq2etn3639ugj` FOREIGN KEY (`to_node_id`) REFERENCES `production_plan_node` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `production_plan_node`;
CREATE TABLE `production_plan_node` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `input_sku` varchar(100) DEFAULT NULL,
  `output_sku` varchar(100) DEFAULT NULL,
  `planned_input_weight` double NOT NULL,
  `planned_output_weight` double NOT NULL,
  `node_role` varchar(20) NOT NULL DEFAULT 'PROCESSING',
  `stage_order` int(11) NOT NULL,
  `status` enum('CANCELLED','COMPLETED','IN_TRANSIT','PLANNED','PROCESSING','READY','READY_TO_PROCESS','WAITING_TRANSPORT') NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `plan_id` bigint(20) NOT NULL,
  `stage_id` bigint(20) NOT NULL,
  `selected_poi_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_production_plan_node_stage` (`plan_id`,`stage_order`),
  KEY `idx_production_plan_node_plan` (`plan_id`),
  KEY `idx_production_plan_node_stage` (`stage_id`),
  KEY `idx_production_plan_node_selected_poi` (`selected_poi_id`),
  CONSTRAINT `FKgglb4o6lirw2tupucyrb972xi` FOREIGN KEY (`stage_id`) REFERENCES `processing_stage` (`id`),
  CONSTRAINT `FKoku3wwftsvhhwbq9nr8ur6wq2` FOREIGN KEY (`plan_id`) REFERENCES `production_plan` (`id`),
  CONSTRAINT `fk_production_plan_node_selected_poi` FOREIGN KEY (`selected_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `route`;
CREATE TABLE `route` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `distance` double DEFAULT NULL,
  `estimated_time` double DEFAULT NULL,
  `fuel_consumption` double DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `route_code` varchar(50) NOT NULL,
  `route_type` varchar(255) DEFAULT NULL,
  `status` enum('ACTIVE','CLOSED','CONGESTED','UNDER_MAINTENANCE') DEFAULT NULL,
  `toll_cost` double DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `end_poi_id` bigint(20) NOT NULL,
  `start_poi_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK4i2x3ep5ajorprml5yd2gucwa` (`route_code`),
  KEY `FKs686s1b0soseu838alldsjwk0` (`end_poi_id`),
  KEY `FK5s08hhs09i5f351687jyma6sg` (`start_poi_id`),
  CONSTRAINT `FK5s08hhs09i5f351687jyma6sg` FOREIGN KEY (`start_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKs686s1b0soseu838alldsjwk0` FOREIGN KEY (`end_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `shipment`;
CREATE TABLE `shipment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cargo_type` varchar(100) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `delivery_appoint` datetime(6) DEFAULT NULL,
  `pickup_appoint` datetime(6) DEFAULT NULL,
  `ref_no` varchar(100) NOT NULL,
  `status` enum('CANCELLED','CREATED','DELIVERED','IN_TRANSIT','PICKED_UP','PLANNED') NOT NULL,
  `demand_source` varchar(20) NOT NULL DEFAULT 'MANUAL',
  `total_volume` double DEFAULT NULL,
  `total_weight` double DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `customer_id` bigint(20) DEFAULT NULL,
  `dest_poi_id` bigint(20) NOT NULL,
  `origin_poi_id` bigint(20) NOT NULL,
  `total_driving_distance` double DEFAULT NULL,
  `total_driving_time` bigint(20) DEFAULT NULL,
  `actual_output_weight` double DEFAULT NULL,
  `chain_code` varchar(50) DEFAULT NULL,
  `chain_name` varchar(100) DEFAULT NULL,
  `expected_output_weight` double DEFAULT NULL,
  `expected_yield_rate` double DEFAULT NULL,
  `processing_actual_finish_time` datetime(6) DEFAULT NULL,
  `processing_expected_finish_time` datetime(6) DEFAULT NULL,
  `is_processing_shipment` bit(1) DEFAULT NULL,
  `processing_start_time` datetime(6) DEFAULT NULL,
  `processing_status` enum('CANCELLED','COMPLETED','IN_PROCESS','PENDING') DEFAULT NULL,
  `processing_chain_id` bigint(20) DEFAULT NULL,
  `loading_wait_time` bigint(20) DEFAULT NULL,
  `unloading_wait_time` bigint(20) DEFAULT NULL,
  `waiting_assignment_time` bigint(20) DEFAULT NULL,
  `allocated_distance_meters` double DEFAULT NULL,
  `allocated_driving_seconds` bigint(20) DEFAULT NULL,
  `loaded_distance_meters` double DEFAULT NULL,
  `loaded_driving_seconds` bigint(20) DEFAULT NULL,
  `loading_wait_seconds` bigint(20) DEFAULT NULL,
  `unloading_wait_seconds` bigint(20) DEFAULT NULL,
  `waiting_assignment_seconds` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_ref_no` (`ref_no`),
  KEY `idx_shipment_status` (`status`),
  KEY `idx_shipment_origin_poi` (`origin_poi_id`),
  KEY `idx_shipment_dest_poi` (`dest_poi_id`),
  KEY `idx_shipment_customer` (`customer_id`),
  KEY `idx_processing_status` (`processing_status`),
  KEY `idx_processing_chain` (`processing_chain_id`),
  CONSTRAINT `FK39yg0rbb9y31dxu205x9mukr5` FOREIGN KEY (`dest_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FK6v966axnajud3h5y73ag6jr3g` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FKeg9iak3b7b6f1v2srabbewxit` FOREIGN KEY (`processing_chain_id`) REFERENCES `processing_chain` (`id`),
  CONSTRAINT `FKetthk8jsm6st5trb1glkap340` FOREIGN KEY (`origin_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `shipment_item`;
CREATE TABLE `shipment_item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `qty` int(11) NOT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `volume` double DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `assignment_id` bigint(20) DEFAULT NULL,
  `goods_id` bigint(20) DEFAULT NULL,
  `shipment_id` bigint(20) NOT NULL,
  `status` enum('ASSIGNED','CANCELLED','DELIVERED','IN_TRANSIT','LOADED','NOT_ASSIGNED') NOT NULL,
  `processed_weight` double DEFAULT NULL,
  `processing_end_time` datetime(6) DEFAULT NULL,
  `processing_start_time` datetime(6) DEFAULT NULL,
  `processing_status` enum('BLOCKED','CANCELLED','COMPLETED','FAILED','PROCESSING','READY','WAITING') DEFAULT NULL,
  `progress_percent` int(11) DEFAULT NULL,
  `stage_name` varchar(100) DEFAULT NULL,
  `stage_order` int(11) DEFAULT NULL,
  `inbound_assignment_id` bigint(20) DEFAULT NULL,
  `outbound_assignment_id` bigint(20) DEFAULT NULL,
  `processing_poi_id` bigint(20) DEFAULT NULL,
  `stage_id` bigint(20) DEFAULT NULL,
  `allocated_distance_meters` double DEFAULT NULL,
  `allocated_driving_seconds` bigint(20) DEFAULT NULL,
  `loading_wait_seconds` bigint(20) DEFAULT NULL,
  `unloading_wait_seconds` bigint(20) DEFAULT NULL,
  `waiting_assignment_seconds` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_item_shipment` (`shipment_id`),
  KEY `idx_item_goods` (`goods_id`),
  KEY `FKfmr6fpw0knyho2gyba1h3c4mi` (`assignment_id`),
  KEY `idx_item_stage` (`stage_id`),
  KEY `idx_item_processing_status` (`processing_status`),
  KEY `FKhbjfr6x24audoyoqe0lob4ill` (`inbound_assignment_id`),
  KEY `FKja7xh8oukhx3xid7see55qilg` (`outbound_assignment_id`),
  KEY `FKivc7e8mtyc0ne8veuijm9o13d` (`processing_poi_id`),
  CONSTRAINT `FKfmr6fpw0knyho2gyba1h3c4mi` FOREIGN KEY (`assignment_id`) REFERENCES `assignment` (`id`),
  CONSTRAINT `FKfrq6k6hp2g0jebbfi1i1tvb03` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`),
  CONSTRAINT `FKg19ptjgocc0cnogtferg9yhin` FOREIGN KEY (`stage_id`) REFERENCES `processing_stage` (`id`),
  CONSTRAINT `FKg9el7ry7yhoj8nwhe98iajd4d` FOREIGN KEY (`shipment_id`) REFERENCES `shipment` (`id`),
  CONSTRAINT `FKhbjfr6x24audoyoqe0lob4ill` FOREIGN KEY (`inbound_assignment_id`) REFERENCES `assignment` (`id`),
  CONSTRAINT `FKivc7e8mtyc0ne8veuijm9o13d` FOREIGN KEY (`processing_poi_id`) REFERENCES `poi` (`id`),
  CONSTRAINT `FKja7xh8oukhx3xid7see55qilg` FOREIGN KEY (`outbound_assignment_id`) REFERENCES `assignment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `shipment_upstream_relations`;
CREATE TABLE `shipment_upstream_relations` (
  `shipment_id` bigint(20) NOT NULL,
  `upstream_shipment_id` bigint(20) DEFAULT NULL,
  KEY `FKq57uk56gbjnelhh1hfyifym9m` (`shipment_id`),
  CONSTRAINT `FKq57uk56gbjnelhh1hfyifym9m` FOREIGN KEY (`shipment_id`) REFERENCES `shipment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `task_wait_episode`;
CREATE TABLE `task_wait_episode` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `assignment_confirmed_sim_time` datetime(6) NOT NULL,
  `assignment_id` bigint(20) NOT NULL,
  `earliest_demand_created_sim_time` datetime(6) NOT NULL,
  `first_execution_sim_time` datetime(6) DEFAULT NULL,
  `last_observed_sim_time` datetime(6) NOT NULL,
  `outcome` enum('CANCELLED','FAILED','STARTED','WAITING_FOR_EXECUTION') NOT NULL,
  `simulation_run_id` varchar(100) NOT NULL,
  `terminal_sim_time` datetime(6) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_wait_run_assignment` (`simulation_run_id`,`assignment_id`),
  KEY `idx_task_wait_run` (`simulation_run_id`),
  KEY `idx_task_wait_run_outcome` (`simulation_run_id`,`outcome`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `vehicle`;
CREATE TABLE `vehicle` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `brand` varchar(50) DEFAULT NULL,
  `cargo_volume` double DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `current_latitude` decimal(10,0) DEFAULT NULL,
  `current_load` double DEFAULT NULL,
  `current_longitude` decimal(10,0) DEFAULT NULL,
  `current_status` enum('BREAKDOWN','IDLE','LOADING','ORDER_DRIVING','TRANSPORT_DRIVING','UNLOADING','WAITING','SCRAPPED','RESERVED_REPLACEMENT') DEFAULT NULL,
  `replacement_reservation_event_id` bigint DEFAULT NULL,
  UNIQUE KEY `uk_vehicle_replacement_reservation` (`replacement_reservation_event_id`),
  `current-volumn` double DEFAULT NULL,
  `driver_name` varchar(50) DEFAULT NULL,
  `height` double DEFAULT NULL,
  `length` double DEFAULT NULL,
  `license_plate` varchar(25) NOT NULL,
  `max_load_capacity` double DEFAULT NULL,
  `model_type` varchar(100) DEFAULT NULL,
  `previous_status` enum('BREAKDOWN','IDLE','LOADING','ORDER_DRIVING','TRANSPORT_DRIVING','UNLOADING','WAITING','SCRAPPED','RESERVED_REPLACEMENT') DEFAULT NULL,
  `status_duration_seconds` bigint(20) DEFAULT NULL,
  `status_start_time` datetime(6) DEFAULT NULL,
  `suitable-goods` varchar(255) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vehicle_type` varchar(50) DEFAULT NULL,
  `width` double DEFAULT NULL,
  `current_poi_id` bigint(20) DEFAULT NULL,
  `is_online` bit(1) DEFAULT NULL,
  `last_position_update` datetime(6) DEFAULT NULL,
  `modbus_slave_id` int(11) DEFAULT NULL,
  `loop-count` int(11) DEFAULT 0,
  `empty_driving_distance` double DEFAULT NULL,
  `empty_driving_time` bigint(20) DEFAULT NULL,
  `loading_wait_time` bigint(20) DEFAULT NULL,
  `total_driving_distance` double DEFAULT NULL,
  `total_driving_time` bigint(20) DEFAULT NULL,
  `has_temp_control` bit(1) DEFAULT NULL,
  `hazmat_qualification` varchar(20) DEFAULT NULL,
  `special_vehicle_type` varchar(50) DEFAULT NULL,
  `unloading_wait_time` bigint(20) DEFAULT NULL,
  `waiting_assignment_time` bigint(20) DEFAULT NULL,
  `empty_distance_meters` double DEFAULT NULL,
  `empty_driving_seconds` bigint(20) DEFAULT NULL,
  `loaded_distance_meters` double DEFAULT NULL,
  `loaded_driving_seconds` bigint(20) DEFAULT NULL,
  `loading_wait_seconds` bigint(20) DEFAULT NULL,
  `total_distance_meters` double DEFAULT NULL,
  `total_driving_seconds` bigint(20) DEFAULT NULL,
  `unloading_wait_seconds` bigint(20) DEFAULT NULL,
  `waiting_assignment_seconds` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKj5v3su3bdx4bvsk1t9dga4bsq` (`license_plate`),
  KEY `FK8h7nsg213m1ofaf42dmqf52oh` (`current_poi_id`),
  CONSTRAINT `FK8h7nsg213m1ofaf42dmqf52oh` FOREIGN KEY (`current_poi_id`) REFERENCES `poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `vehicle_goods_match`;
CREATE TABLE `vehicle_goods_match` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `destination_poi_id` bigint(20) DEFAULT NULL,
  `destination_poi_name` varchar(200) DEFAULT NULL,
  `distance_km` decimal(10,2) DEFAULT NULL COMMENT '距离 (公里)',
  `goods_id` bigint(20) NOT NULL,
  `goods_name` varchar(200) DEFAULT NULL,
  `goods_sku` varchar(100) DEFAULT NULL,
  `hazmat_level` varchar(20) DEFAULT NULL,
  `is_fully_matched` bit(1) DEFAULT NULL,
  `license_plate` varchar(25) DEFAULT NULL,
  `match_description` varchar(1000) DEFAULT NULL,
  `match_score` decimal(5,2) DEFAULT NULL COMMENT '匹配评分 (0-100)',
  `match_status` enum('CANCELLED','COMPLETED','CONFIRMED','PENDING','REJECTED') NOT NULL,
  `match_time` datetime(6) NOT NULL,
  `origin_poi_id` bigint(20) DEFAULT NULL,
  `origin_poi_name` varchar(200) DEFAULT NULL,
  `require_temp_control` bit(1) DEFAULT NULL,
  `required_volume` decimal(10,2) DEFAULT NULL COMMENT '货物体积需求 (m³)',
  `required_weight` decimal(10,2) DEFAULT NULL COMMENT '货物重量需求 (吨)',
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(50) DEFAULT NULL,
  `vehicle_cargo_volume` decimal(10,2) DEFAULT NULL COMMENT '车辆容积能力 (m³)',
  `vehicle_id` bigint(20) NOT NULL,
  `vehicle_load_capacity` decimal(10,2) DEFAULT NULL COMMENT '车辆载重能力 (吨)',
  `volume_utilization` decimal(5,4) DEFAULT NULL COMMENT '容积利用率',
  `weight_utilization` decimal(5,4) DEFAULT NULL COMMENT '重量利用率',
  PRIMARY KEY (`id`),
  KEY `idx_match_goods_id` (`goods_id`),
  KEY `idx_match_vehicle_id` (`vehicle_id`),
  KEY `idx_match_time` (`match_time`),
  KEY `idx_match_status` (`match_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
DROP TABLE IF EXISTS `vehicle_wait_episode`;
CREATE TABLE `vehicle_wait_episode` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `end_reason` enum('ASSIGNMENT_CONFIRMED','LEFT_AVAILABLE_IDLE') DEFAULT NULL,
  `ended_sim_time` datetime(6) DEFAULT NULL,
  `last_observed_sim_time` datetime(6) NOT NULL,
  `simulation_run_id` varchar(100) NOT NULL,
  `started_sim_time` datetime(6) NOT NULL,
  `status` enum('CLOSED','OPEN') NOT NULL,
  `vehicle_id` bigint(20) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vehicle_wait_run_vehicle_start` (`simulation_run_id`,`vehicle_id`,`started_sim_time`),
  KEY `idx_vehicle_wait_run` (`simulation_run_id`),
  KEY `idx_vehicle_wait_run_status` (`simulation_run_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- Event/weather compatibility tables are empty after all sandbox preparation stages.
CREATE TABLE `weather_scenario` (
  `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255),
  `definition_json` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `weather_run` (
  `id` varchar(255) NOT NULL PRIMARY KEY, `scenario_id` bigint,
  `external_experiment_id` varchar(255), `started_at` datetime(6), `ended_at` datetime(6),
  `manually_intervened` bit NOT NULL, `frozen_scenario_json` longtext,
  `frozen_event_configuration_json` longtext, `weather_timeline_sha256` varchar(64),
  `event_history_json` longtext, `driving_history_json` longtext,
  `execution_segment_history_json` longtext, `replacement_attempt_history_json` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `driving_progress` (
  `phase_key` varchar(240) NOT NULL PRIMARY KEY, `run_id` varchar(255), `vehicle_id` bigint,
  `assignment_id` bigint, `leg_index` int, `driving_status` varchar(255),
  `phase_start` datetime(6), `last_settled_time` datetime(6), `initial_work_seconds` double NOT NULL,
  `remaining_work_seconds` double NOT NULL, `affected_seconds` double NOT NULL,
  `lost_work_seconds` double NOT NULL, `model_completed_time` datetime(6), `observed_completed_time` datetime(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `transport_random_event` (
  `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `run_id` varchar(36),
  `trigger_loop_index` int, `random_protocol_id` varchar(80),
  `event_type` varchar(40) NOT NULL, `status` varchar(20) NOT NULL, `trigger_source` varchar(20) NOT NULL,
  `vehicle_id` bigint NOT NULL, `license_plate` varchar(50), `assignment_id` bigint NOT NULL,
  `start_time` datetime(6) NOT NULL, `planned_end_time` datetime(6), `resolved_time` datetime(6),
  `speed_factor` double, `previous_vehicle_status` varchar(30), `remaining_status_seconds` bigint,
  `delay_seconds` bigint, `random_seed` bigint, `description` varchar(255),
  `breakdown_level` varchar(30), `breakdown_phase` varchar(30), `rescue_wait_minutes` int,
  `repair_minutes` int, `repair_start_time` datetime(6), `recovery_processed_time` datetime(6),
  `recovery_outcome` varchar(80), `breakdown_rule_version` varchar(40), `original_assignment_status` varchar(20),
  `original_leg_index` int, `original_driving_phase_key` varchar(240), `replacement_wait_minutes` int,
  `replacement_vehicle_id` bigint, `original_driver_id` bigint, `replacement_driver_id` bigint,
  `replacement_license_plate` varchar(50), `replacement_selected_time` datetime(6),
  `replacement_ready_time` datetime(6), `replacement_processed_time` datetime(6), `replacement_outcome` varchar(80),
  `required_load` double, `required_volume` double,
  UNIQUE KEY `uk_transport_event_auto_tick` (`run_id`,`vehicle_id`,`trigger_loop_index`),
  KEY `idx_transport_event_status` (`status`), KEY `idx_transport_event_vehicle_status` (`vehicle_id`,`status`),
  KEY `idx_transport_event_assignment` (`assignment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `vehicle_replacement_attempt` (
  `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `run_id` varchar(36), `event_id` bigint NOT NULL,
  `assignment_id` bigint NOT NULL, `original_vehicle_id` bigint NOT NULL, `original_license_plate` varchar(50),
  `replacement_vehicle_id` bigint NOT NULL, `replacement_license_plate` varchar(50),
  `original_driver_id` bigint, `replacement_driver_id` bigint, `selected_time` datetime(6) NOT NULL,
  `ready_time` datetime(6) NOT NULL, `handoff_time` datetime(6), `wait_minutes` int NOT NULL,
  `required_load` double NOT NULL, `required_volume` double NOT NULL, `status` varchar(20) NOT NULL,
  `outcome` varchar(80), `rule_version` varchar(40), KEY `idx_replacement_attempt_event` (`event_id`),
  KEY `idx_replacement_attempt_run` (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `transport_execution_segment` (
  `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `run_id` varchar(36) NOT NULL,
  `assignment_id` bigint NOT NULL, `leg_id` bigint NOT NULL, `loop_index` int NOT NULL, `fragment_index` int NOT NULL,
  `vehicle_id` bigint NOT NULL, `driver_id` bigint NOT NULL, `from_sim_time` datetime(6) NOT NULL,
  `to_sim_time` datetime(6) NOT NULL, `distance_meters` double NOT NULL, `driving_seconds` bigint NOT NULL,
  `capacity_tonnes` double DEFAULT NULL, `load_tonnes` double NOT NULL, `load_state` varchar(20) NOT NULL,
  `travel_time_factor` double NOT NULL, `energy_liters` double NOT NULL, `emission_kg` double NOT NULL,
  `energy_valid` bit NOT NULL, `emission_model_id` varchar(80), `vehicle_class_code` varchar(40),
  UNIQUE KEY `uk_execution_segment_tick` (`leg_id`,`loop_index`,`fragment_index`),
  KEY `idx_execution_segment_run` (`run_id`), KEY `idx_execution_segment_vehicle` (`vehicle_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
